### ISSUE TITLE
[handlebars] Deploy on-prem instructions missing a step

### ISSUE THREAD

**Issue by theonegri** [microsoft/FHIR-Converter#185]
The instruction for deploy the handlebars engine are:
```
git clone https://github.com/microsoft/FHIR-Converter/
cd FHIR-Converter
npm install
npm start
```

Since the handlebars engine is now in a dedicated branch it's missing the instruction `git checkout handlebars`

Also is the plan to de-prioritized development and support for the handlebar engine(since introduction of Liquid Engine)?

**Comment by theonegri** [comment]
@ranvijaykumar I'm more than happy to submit a PR to update the instructions if that can help!

**Comment by ranvijaykumar** [comment]
That will be great.

**Comment by theonegri** [comment]
@ranvijaykumar here you go https://github.com/microsoft/FHIR-Converter/pull/186
