### ISSUE TITLE
Liquid Engine VS Handlebars Engine

### ISSUE THREAD

**Issue by theonegri** [microsoft/FHIR-Converter#188]
Since the team is moving toward implementing support for Liquid Engine, are still going to support Handlebars Engine?

Is the plan to retire Handlebars once Liquid is fully implemented? We are currently evaluating a FHIRv2/CDA to FHIR translation tool and this is a critical point for us.

**Comment by ranvijaykumar** [comment]
We have no plans to retire the Handlebars engine. Liquid engine has advantages over Handlebars engine though. Liquid engine is now integrated into Azure API for FHIR as well as FHIR Server for Azure. So, you if are using any of the two servers, you do not need an additional conversion service. Liquid engine is also available as a command line tool.

**Comment by theonegri** [comment]
I understand the advantages of Liquid however we aren't running our stack on Azure.
