### ISSUE TITLE
metadata error

### ISSUE THREAD

**Issue by cunninghamb505** [microsoft/FHIR-Converter#205]
When I try to follow the steps in VS code I get an error saying it cant find metadata?

**Comment by sowu880** [comment]
When convert data using VS code, please make sure to select a template folder which is the root folder and contains a "metadata.json" file and other root templates. Here is the root folder for default templates that contains metadata. [https://github.com/microsoft/FHIR-Converter/tree/main/data/Templates/Hl7v2](url)

**Comment by cunninghamb505** [comment]
@sowu880 thank you, I was able to figure that out. I think others might run into the same issue. I had trouble reading the gif video.
