### ISSUE TITLE
Mapping output in Liquid 

### ISSUE THREAD

**Issue by cunninghamb505** [microsoft/FHIR-Converter#206]
I am noticing some items not being outputted in the starter template. Example: PV1.3 the location is not outputting the value in the bundle template after converting. I only see the location reference GUID being generated and not the actual value from HL7 (PREOD). I attached a screenshot. I see in the template it has PV1.3 am I missing something? 

Thank you,
Brandon

![image](https://user-images.githubusercontent.com/12199633/107391142-67a70500-6ac6-11eb-8e4b-5a734622af8e.png)

**Comment by cunninghamb505** [comment]
Looks like i might have figured it out. I had to look at a sub reference template. Having some trouble learning how to map HL7 to the templates. Is there any video out there showcasing how to map a basic field? Thank you , powerful stuff

**Comment by ranvijaykumar** [comment]
Glad that you were able to figure it out. We currently do not have a video. The documentation on the marketplace is the best help we currently have.  https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-health-fhir-converter
