### ISSUE TITLE
400 error when pushing converted bundle

### ISSUE THREAD

**Issue by cunninghamb505** [microsoft/FHIR-Converter#209]
Hi, I am using the $convert-data api call to convert the HL7 then make a call to post the bundle. When I try to push the bundle below my response says 400 error. It still posts but not sure what this error means? Can you explain , Thank you

[bundle.txt](https://github.com/microsoft/FHIR-Converter/files/6037482/bundle.txt)

**Comment by ranvijaykumar** [comment]
Try validating your resource with FHIR validator, to see what errors it reports. You may need to make changes in the template to make it compliant. https://wiki.hl7.org/Using_the_FHIR_Validator
