### ISSUE TITLE
Custom templates are getting deleted automatically.

### ISSUE THREAD

**Issue by AyRawat** [microsoft/FHIR-Converter#214]
I am using FHIR-Converter to convert HL7 Messages to FHIR resource in my project. The code is inside a container and is deployed into the Azure Cloud. I have also created a custom template according to my needs.  But after using it for some time the template automatically gets deleted. Only the Pre built templates like 'ADT_A01' , 'ORU_O01' etc. remains.  I have to create my template again and again . This is disrupting the flow of my  project where I am using it. This has happened a couple of times in last three months.  Also the  repo on my local machine, where I initially tested my template is working absolutely fine. I never faced any issue in my local machine.  If anyone knows about this issue please help me.

**Comment by ranvijaykumar** [comment]
It seems you are hitting this issue: https://github.com/microsoft/FHIR-Converter/blob/handlebars/docs/web-ui-auto-update-issue.md

**Comment by AyRawat** [comment]
I think this is the solution, I have been looking for.
