### ISSUE TITLE
Chnage to async handlerbars

### ISSUE THREAD

**Issue by fhirfly** [microsoft/FHIR-Converter#217]

**Comment by fhirfly** [comment]
FHIR converter is great, but your handlebars is not async, so making calls to anything external, like a database call to get patient id's, causes blocking issues.  I suggest upgrading your handlebars to async, so that this is more production ready.  We have already proven this in concept in a private fork.  It should be easy enough for you to do.

**Comment by qiwjin** [comment]
Thanks for your suggestion, we will put it into our backlog and discuss this requirement within our team first.
