### ISSUE TITLE
format_as_date_time - time zone conversion

### ISSUE THREAD

**Issue by jamesnovak** [microsoft/FHIR-Converter#221]
testing using the VS code extensions locally.  **format_as_date_time** seems to convert to local time.  

Is there a way to convert to the TZ specified in the string?  

It seems to honor this value during conversion, but always returns the TZ in the result as my local TZ.  Examples from my testing so far

**UTC TZ conversion**
{%- assign _date2Format="20200806133040+0000" -%}
{% assign _formatDate = _date2Format | format_as_date_time  %}
"formatDate": "2020-08-06T09:30:40-04:00"

**UTC +/-3  TZ conversion**
{%- assign _date2Format="20200806133040+0300" -%}
"formatDate": "2020-08-06T06:30:40-04:00"

{%- assign _date2Format="20200806133040-0300" -%}
"formatDate": "2020-08-06T12:30:40-04:00"

**Comment by qiwjin** [comment]
Thanks for your feedback, we will add timezone support in next release. stay tuned.

**Comment by jamesnovak** [comment]
Thanks!  Do you accept pull requests?  
I wanted to submit some date add methods, similar to those offered by Power Apps Portals : https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/liquid-filters#date-filters
I have the code now and I am working on adding the unit tests.
