### ISSUE TITLE
Matching the correct MRN ID

### ISSUE THREAD

**Issue by cunninghamb505** [microsoft/FHIR-Converter#243]
How does the tool know its the correct patient during conversion? How does it know when I send one ADT that has MRN 123 vs a different patient that has the same MRN 123?  can you explain your matching criteria 

" set of templates help generate FHIR resource IDs from HL7 v2 messages. An ID generation template does 3 things: 1) extract identifiers from input segment or field; 2) combine the identifers with resource type and base ID (optional) as hash seed; 3) compute hash as output ID."

**Comment by ranvijaykumar** [comment]
It uses the concatenation of PID3.1 and PID3.4 as seed to generate the Patient Id. See the file ID/_Patient.Liquid  If you send two messages with the same PID3.1 and PID3.4 combination, it will generate the same patient id. It should work in most of the scenarios. However, if this logic does not work for your scenario, you should change it in ID/_Patient.Liquid

**Comment by cunninghamb505** [comment]
Thank you,
Assuming that is the same logic for PID 18 visit number to encounter

**Comment by ranvijaykumar** [comment]
Visit number is PV1.19, isn't it? Yes, you can see the logic in ID/_Encounter.liquid

**Comment by cunninghamb505** [comment]
Thanks yes, and i am guessing if I am sending ADT from two different facility's it would not matter. I would need to keep track from the organization or location resource?

**Comment by ranvijaykumar** [comment]
I am not sure if I fully understand your question. It all depends on what data you are receiving from your facilities.

**Comment by cunninghamb505** [comment]
no worries, Thank you I figured it out. I was thinking of mapping the MSH to location resource.
