### ISSUE TITLE
ID/_Practitioner does not support practitioners listed in PV1.

### ISSUE THREAD

**Issue by jchen75006** [microsoft/FHIR-Converter#250]
HL7 PV1 has the following practitioners listed and current ID/_Practitioner does not support their GUID calculation. I cannot use your current template to calculate their GUIDs.

PV1.7 Attending Doctor
PV1.8 Referring Doctor
PV1.9 Consulting Doctor
PV1.17 Admitting Doctor
PV1.52 Other Healthcare Provider

As a workaround, I am creating a new ID/_PractitionerPV1 with the content below to support my business need. Let me know if you want me to add this to my branch and my pull request.

{% capture identifiers -%}
{% if XCN.3 and XCN.7 -%}{{XCN.3.Value}},{{XCN.7.Value}}
{% elsif XCN.3 and XCN.8 -%}{{XCN.3.Value}},{{XCN.8.Value}}
{% elsif XCN.3 and XCN.9 -%}{{XCN.3.Value}},{{XCN.9.Value}}
{% elsif XCN.3 and XCN.17 -%}{{XCN.3.Value}},{{XCN.17.Value}}
{% elsif XCN.3 and XCN.52 -%}{{XCN.3.Value}},{{XCN.52.Value}}
{% endif -%}
{% endcapture -%}
{{ identifiers | generate_id_input: 'Practitioner', false | generate_uuid }}

**Comment by ACMoretxj** [comment]
Thanks for your feedback and workaround. Another way of organizing resource templates is being discussed internally, which might be different from yours. But you can customize the templates arbitrarily in your branch and use disparate ways from the default templates.

**Comment by jchen75006** [comment]
Ok. Thanks.
