### ISSUE TITLE
CCDA Conversion Failing

### ISSUE THREAD

**Issue by gmontagu** [microsoft/FHIR-Converter#251]
The CCDA Conversion process fails with the error "Process failed: The conversion from data type 'cda' to FHIR is not supported"

Changing the metadata.json under data/Templates/Ccda/ to 'ccda' fixes the process.

**Comment by BoyaWu10** [comment]
Thanks for sharing this! This has been [fixed](https://github.com/microsoft/FHIR-Converter/pull/226) in our dev branch and it will take effect in next release.
