### ISSUE TITLE
Where/how can I store EVN data?

### ISSUE THREAD

**Issue by jchen75006** [microsoft/FHIR-Converter#260]
My healthcare vendor would provide HL7 EVN message segment to indicate when an event such as A01 (admission), A03 (discharge), A08 (patient update), A04 (referral), and A11 (cancel admission). The event timestamp is generally different from the message header timestamp. So, I need to store the event timestamp as it occurred. Is there an FHIR entity to store EVN data?

Here is a sample of the data. Note the EVN timestamp is different from message header timestamp. Without the EVN timestamp, I would miss the event by 1 day.

MSH|^~\&|J3rdsU1S/YU3pMoUwk/9ZQ==|CB99V96UUEJVQA7DK5G6APHVVG|Hospice Source||20210615165034||ADT^A08|20210615165034HEP00001905502|T|2.5||||||ASCII
EVN|A08|20210614111226|20210614111226|01||20210614111226

**Comment by ranvijaykumar** [comment]
Recommend posting this question on chat.fhir.org
