### ISSUE TITLE
Where can I store patient race/ethnicity data?

### ISSUE THREAD

**Issue by jchen75006** [microsoft/FHIR-Converter#261]
I have patient/ethnicity data from healthcare vendors in HL7. Where can I store/map it in FHIR?

FHIR standard: https://www.hl7.org/fhir/v3/Race/cs.html and https://www.hl7.org/fhir/patient-profiles.html

My HL7 vendor test data have race as "WHITE" in the PID segment below.

MSH|^~\&|J3rdsU1S/YU3pMoUwk/9ZQ==|CB99V96UUEJVQA7DK5G6APHVVG|Hospice Source||20210623103315||ADT^A01|20210623103315HEP00001905602|T|2.5||||||ASCII
EVN|A01|20210622144027|20210622144027|01||20210622144027
PID|1||19056|16364|JOHNSON^JAMES^||19450224|M||WHITE|1440 KNOTTS WAY^^EL PASO^MI^79910^^PATIENT'S HOME/RESIDENCE^^||(915)222-5566||English|WIDOW||HEP00000005602|456231920|||||||||||N

**Comment by ranvijaykumar** [comment]
You would use extensions for this. Check out US Core extensions for race and ethnicity. Also, chat.fhir.org is a great place to get answers to such questions.

**Comment by jchen75006** [comment]
Ranvijay, My issues are related to "gaps" of the converter, not about FHIR information. The converter misses converting those data. Can I re-open them?

**Comment by CaitlinV39** [comment]
@jchen75006 The templates provided are just a starting place and likely will need to be modified for your needs. The converter is setup to be a flexible tool so that you can develop your own templates. You can modify the template to map the ethnicity data to the FHIR field that you want.

**Comment by jchen75006** [comment]
@CaitlinV39 I have fixed other gaps on my side. But, this one and another two I could not figure out how to add them. Need help.

**Comment by jchen75006** [comment]
@CaitlinV39 Another challenge I have when I try to fill these data gaps is that the FHIR API server may not take the data even if I manage to update the template to add them. Since I do not have the inner working of the FHIR API server, it is really difficult for me to add them, compared to your team.

**Comment by ranvijaykumar** [comment]
> Ranvijay, My issues are related to "gaps" of the converter, not about FHIR information. The converter misses converting those data. Can I re-open them?

Can you share your sample data, current template, and expected behavior? We will have a look at it.

**Comment by ranvijaykumar** [comment]
> @CaitlinV39 Another challenge I have when I try to fill these data gaps is that the FHIR API server may not take the data even if I manage to update the template to add them. Since I do not have the inner working of the FHIR API server, it is really difficult for me to add them, compared to your team. The question is where in the template to be the right place to add these data so they can be processed and stored by the FHIR API server? I just do not have this knowledge unless I were in your team.

Have you tried validating your resources with [FHIR Validator](https://wiki.hl7.org/Using_the_FHIR_Validator)? Validator does a good job of giving error details with the resources.

**Comment by jchen75006** [comment]
Sample [data](https://1drv.ms/u/s!AtncvjsCLPFfggWS8-gBCb37enkK) and [template](https://1drv.ms/u/s!AtncvjsCLPFfggQxc_AIbf4_Ca2Y?e=eY52LS) One Drive links are provided. 

In the PID segment, field 10 has value "WHITE". Expect it to be populated in FHIR converter output.

**Comment by jchen75006** [comment]
> > @CaitlinV39 Another challenge I have when I try to fill these data gaps is that the FHIR API server may not take the data even if I manage to update the template to add them. Since I do not have the inner working of the FHIR API server, it is really difficult for me to add them, compared to your team. The question is where in the template to be the right place to add these data so they can be processed and stored by the FHIR API server? I just do not have this knowledge unless I were in your team.
> 
> Have you tried validating your resources with [FHIR Validator](https://wiki.hl7.org/Using_the_FHIR_Validator)? Validator does a good job of giving error details with the resources.

I'll check out the validator. I am using FHIR API server to verify data, which should be the best option although it is not the most convenient. Thanks.

**Comment by jchen75006** [comment]
> > @CaitlinV39 Another challenge I have when I try to fill these data gaps is that the FHIR API server may not take the data even if I manage to update the template to add them. Since I do not have the inner working of the FHIR API server, it is really difficult for me to add them, compared to your team. The question is where in the template to be the right place to add these data so they can be processed and stored by the FHIR API server? I just do not have this knowledge unless I were in your team.
> 
> Have you tried validating your resources with [FHIR Validator](https://wiki.hl7.org/Using_the_FHIR_Validator)? Validator does a good job of giving error details with the resources.

Checked it and it does not work for me. I have the followng error "Cannot invoke "com.google.gson.JsonObject.has(String)" because "paths" is null".

**Comment by jchen75006** [comment]
> > > @CaitlinV39 Another challenge I have when I try to fill these data gaps is that the FHIR API server may not take the data even if I manage to update the template to add them. Since I do not have the inner working of the FHIR API server, it is really difficult for me to add them, compared to your team. The question is where in the template to be the right place to add these data so they can be processed and stored by the FHIR API server? I just do not have this knowledge unless I were in your team.
> > 
> > 
> > Have you tried validating your resources with [FHIR Validator](https://wiki.hl7.org/Using_the_FHIR_Validator)? Validator does a good job of giving error details with the resources.
> 
> Checked it and it does not work for me. I have the followng error "Cannot invoke "com.google.gson.JsonObject.has(String)" because "paths" is null".

Correction. The link has bad JAR file. Once I use the one on Confluence site, it works. Thanks.
