### ISSUE TITLE
Current converter template does not convert HL7 race/ethnicity data into FHIR

### ISSUE THREAD

**Issue by jchen75006** [microsoft/FHIR-Converter#266]
I have patient/ethnicity data from healthcare vendors in HL7. They are not converted by the template.

FHIR standard: https://www.hl7.org/fhir/v3/Race/cs.html and https://www.hl7.org/fhir/patient-profiles.html

My HL7 vendor test data have race as "WHITE" in the PID segment below.

MSH|^~&|J3rdsU1S/YU3pMoUwk/9ZQ==|CB99V96UUEJVQA7DK5G6APHVVG|Hospice Source||20210623103315||ADT^A01|20210623103315HEP00001905602|T|2.5||||||ASCII
EVN|A01|20210622144027|20210622144027|01||20210622144027
PID|1||19056|16364|JOHNSON^JAMES^||19450224|M||WHITE|1440 KNOTTS WAY^^EL PASO^MI^79910^^PATIENT'S HOME/RESIDENCE^^||(915)222-5566||English|WIDOW||HEP00000005602|456231920|||||||||||N

The challenge I have is where in the template can I add them so the FHIR API server would store the new data. Sometimes I cannot find the place in the template to add the data; sometimes if I could add them, they do not show up in the server.

**Comment by jchen75006** [comment]
Sample [data](https://1drv.ms/u/s!AtncvjsCLPFfggWS8-gBCb37enkK) and [template](https://1drv.ms/u/s!AtncvjsCLPFfggQxc_AIbf4_Ca2Y?e=eY52LS) One Drive links are provided. 

In the PID segment, field 10 has value "WHITE". Expect it to be populated in FHIR converter output.

**Comment by ranvijaykumar** [comment]
From [V2 to FHIR spreadsheet](https://docs.google.com/spreadsheets/d/1_MOAJOykRWct_9cBG-EcPcWSpSObQFLboPB579DIoAI/edit#gid=0):
_"PID-10 is may map different based on local requirements and should use the local extension, e.g., US = UC Core Race extension, AUS = indigenous extension."_

If you are creating the template for the USA, you should modify the templates to use US Core profile. Here is the snippet you can use to map your PID.10 value to US Core race profile. You will need to modify the _Patient.liquid file.

Based on your sample, it seems you are only getting the text field in PID.10. If you get more fields in PID.10 then you will need to extract the values using field locators such as r.1.Value, or r.2.Value.

```json

"id":"{{ ID }}",
        "extension": [
            {% for r in PID.10.Repeats -%}
            {
                "url": "http://hl7.org/fhir/StructureDefinition/us-core-race",
                "extension": [
                    {
                        "url": "ombCategory",
                        "valueCoding": {
                            "system": "http://hl7.org/fhir/v3/Race",
                            "display": "{{r.Value}}"
                        }
                    }
                ]
            },
            {% endfor -%}            
        ],
        "identifier":

```

Hope this helps.

**Comment by jchen75006** [comment]
> From [V2 to FHIR spreadsheet](https://docs.google.com/spreadsheets/d/1_MOAJOykRWct_9cBG-EcPcWSpSObQFLboPB579DIoAI/edit#gid=0):
> _"PID-10 is may map different based on local requirements and should use the local extension, e.g., US = UC Core Race extension, AUS = indigenous extension."_
> 
> If you are creating the template for the USA, you should modify the templates to use US Core profile. Here is the snippet you can use to map your PID.10 value to US Core race profile. You will need to modify the _Patient.liquid file.
> 
> Based on your sample, it seems you are only getting the text field in PID.10. If you get more fields in PID.10 then you will need to extract the values using field locators such as r.1.Value, or r.2.Value.
> 
> ```json
> "id":"{{ ID }}",
>         "extension": [
>             {% for r in PID.10.Repeats -%}
>             {
>                 "url": "http://hl7.org/fhir/StructureDefinition/us-core-race",
>                 "extension": [
>                     {
>                         "url": "ombCategory",
>                         "valueCoding": {
>                             "system": "http://hl7.org/fhir/v3/Race",
>                             "display": "{{r.Value}}"
>                         }
>                     }
>                 ]
>             },
>             {% endfor -%}            
>         ],
>         "identifier":
> ```
> 
> Hope this helps.

FHIR API server can process it but the race data do not show up in Patient record, when I query the server.

**Comment by ranvijaykumar** [comment]
a) Are you saying that the resource that the FHIR server returns does not contain the race extension? 
b) When you POST the FHIR resource, do you see the race extension in the response body?

**Comment by jchen75006** [comment]
After checking it with Postman, it works. It was error in my automation script. For your solution, I would never be able to figure it out without your help. The issue is resolved. Thanks.
