### ISSUE TITLE
Converter does not convert HL7 EVN message into FHIR.

### ISSUE THREAD

**Issue by jchen75006** [microsoft/FHIR-Converter#267]
My healthcare vendor would provide HL7 EVN message segment to indicate when an event such as A01 (admission), A03 (discharge), A08 (patient update), A04 (referral), and A11 (cancel admission). The event timestamp is generally different from the message header timestamp. So, I need to store the event timestamp as it occurred. Converter does not convert HL7 EVN message into FHIR. Is there a workaround available?

Here is a sample of the data. Note the EVN timestamp is different from message header timestamp. Without the EVN timestamp, I would miss the event by 1 day.

MSH|^~&|J3rdsU1S/YU3pMoUwk/9ZQ==|CB99V96UUEJVQA7DK5G6APHVVG|Hospice Source||20210615165034||ADT^A08|20210615165034HEP00001905502|T|2.5||||||ASCII
EVN|A08|20210614111226|20210614111226|01||20210614111226

The challenge I have is where in the template can I add them so the FHIR API server would store the new data. Sometimes I cannot find the place in the template to add the data; sometimes if I could add them, they do not show up in the server.

**Comment by ranvijaykumar** [comment]
The first thing to decide is the FHIR field where you want to store the event timestamp. Do you want to store it in provenance resource, message header resource, or somewhere else. Once you have made that decision, we may be able to help you with the changes you will need to do in your template.

**Comment by jchen75006** [comment]
> The first thing to decide is the FHIR field where you want to store the event timestamp. Do you want to store it in provenance resource, message header resource, or somewhere else. Once you have made that decision, we may be able to help you with the changes you will need to do in your template.

Can we create it as a new "Encounter" resource? I cannot consider MessageHeader resource, because it does not link to a Patient. I need something to link to a patient.

**Comment by ranvijaykumar** [comment]
The default templates already create an encounter resource. The period.start and period.end in the encounter are coming from PV1.44. If you want to use EVN to populate the period, you may pass firstSegments.EVN  as an additional parameter to the following call in the ADT_A01.liquid file. 

```json
{% include 'Resource/Encounter' PV1: firstSegments.PV1, PV2: firstSegments.PV2, Location_ID_PV1_3: locationId_PV1_3, Location_ID_PV1_6: locationId_PV1_6, Practitioner_ID_PV1_7: practitionerId_PV1_7, Practitioner_ID_PV1_8: practitionerId_PV1_8, Practitioner_ID_PV1_9: practitionerId_PV1_9, Practitioner_ID_PV1_17: practitionerId_PV1_17, Practitioner_ID_PV1_52: practitionerId_PV1_52, ID: encounterId -%}       
```
Subsequently, you can use values from the EVN segment in the _Encounter.liquid to populate the start and and time.

**Comment by jchen75006** [comment]
> The default templates already create an encounter resource. The period.start and period.end in the encounter are coming from PV1.44. If you want to use EVN to populate the period, you may pass firstSegments.EVN as an additional parameter to the following call in the ADT_A01.liquid file.
> 
> ```json
> {% include 'Resource/Encounter' PV1: firstSegments.PV1, PV2: firstSegments.PV2, Location_ID_PV1_3: locationId_PV1_3, Location_ID_PV1_6: locationId_PV1_6, Practitioner_ID_PV1_7: practitionerId_PV1_7, Practitioner_ID_PV1_8: practitionerId_PV1_8, Practitioner_ID_PV1_9: practitionerId_PV1_9, Practitioner_ID_PV1_17: practitionerId_PV1_17, Practitioner_ID_PV1_52: practitionerId_PV1_52, ID: encounterId -%}       
> ```
> 
> Subsequently, you can use values from the EVN segment in the _Encounter.liquid to populate the start and and time.

This solution works. Thanks.

**Comment by jchen75006** [comment]
The problems is fixed based on recommended solution. Thanks.

Here are changes to _Encounter.liquid.

        "period":
        {
            {% if PV1.44 -%}
            "start":"{{ PV1.44.Value | format_as_date_time }}",
            {% else %}
            "start":"{{ EVN.6.Value | format_as_date_time }}",
            {% endif -%}
            "end":"{{ PV1.45.Value | format_as_date_time }}",
        },
