### ISSUE TITLE
Converter does not convert HL7 PV1 field 41 account status into FHIR data.

### ISSUE THREAD

**Issue by jchen75006** [microsoft/FHIR-Converter#268]
I have the following HL7 PV1 segment field 41 as account status "CURRENT". It is missed by the converter. Is there a workaround?

PV1|1|O|HOSPICE OF EDMOND, INC.^^^HEP&HOSPICE EDMOND^2^PATIENT'S HOME/RESIDENCE^^^GREEN|NEW ADMISSION|||1900038389^REEVES^BOB^^^^MD|^^^^^^|1538112198^G^LOUIS^^^^MD|||||||||HOSPICE|16364||||||||||||||||||||||CURRENT|||20210622000000

The challenge I have is where in the template can I add them so the FHIR API server would store the new data. Sometimes I cannot find the place in the template to add the data; sometimes if I could add them, they do not show up in the server.

**Comment by ranvijaykumar** [comment]
The account status in FHIR takes [these](https://www.hl7.org/fhir/valueset-account-status.html) values. On the other hand, PV1.41 can take any value as it binds to user defined table. Therefore, you will need to update the templates and map the values as per your requirements.

In order to do so, update the _Patient.liquid file to first pass PV1 segment as an additional parameter to the Account resource:
{% include 'Resource/Account' PID: firstSegments.PID, PV1: firstSegments.PV1, ID: accountId -%}

Next, update the _Account.liquid file with your mapping logic:

```json
......
        "identifier":
        [
            { {% include 'DataType/CX' CX: PID.18 -%} },
        ],
        {% if PV1.41.Value == 'CURRENT' %}
        "status": "active",
        {% else %}
        "status": "unknown",
        {% endif %}
        "subject":
......
```

**Comment by jchen75006** [comment]
> The account status in FHIR takes [these](https://www.hl7.org/fhir/valueset-account-status.html) values. On the other hand, PV1.41 can take any value as it binds to user defined table. Therefore, you will need to update the templates and map the values as per your requirements.
> 
> In order to do so, update the _Patient.liquid file to first pass PV1 segment as an additional parameter to the Account resource:
> {% include 'Resource/Account' PID: firstSegments.PID, PV1: firstSegments.PV1, ID: accountId -%}
> 
> Next, update the _Account.liquid file with your mapping logic:
> 
> ```json
> ......
>         "identifier":
>         [
>             { {% include 'DataType/CX' CX: PID.18 -%} },
>         ],
>         {% if PV1.41.Value == 'CURRENT' %}
>         "status": "active",
>         {% else %}
>         "status": "unknown",
>         {% endif %}
>         "subject":
> ......
> ```

The solution works. Here is what I did to _Account.liquid. Thanks.

        {% if PV1.41 %}
        {% if PV1.41.Value == 'PENDING' %}
        "status": "on-hold",
        {% elsif PV1.41.Value == 'CURRENT' %}
        "status": "active",
        {% else %}
        "status": "{{PV1.41.Value | downcase}}",
        {% endif %}
        {% elsif PID.18 %}
        "status": "active",
        {% else %}
        "status": "unknown",
        {% endif %}

**Comment by jchen75006** [comment]
The problems is fixed based on recommended solution. Thanks.
