### ISSUE TITLE
Missing resourceTypes in output

### ISSUE THREAD

**Issue by TerriblyVexed** [microsoft/FHIR-Converter#334]
I've deployed the Handlebars deployment to my Azure instance. I'm using CDA converter. I'm using ccd.hbs Template.
I have copied in my cda for synthetic patient Sofia Mateo. Even though the ccd template shows 
`{{>Sections/Allergies_and_Adverse_Reactions.hbs}}`
it isn't creating an AllergyIntolerance resourceType in the resultant json. Or a Medication resourceType, or others. What I am getting is Composition, Patient, DocumentReference, and Organization.
Am I using the wrong template? Does it need to be customized to pull these resourceTypes? Is there an existing one that does pull all these?

Here is my cds
[new 4.txt](https://github.com/microsoft/FHIR-Converter/files/7626334/new.4.txt)
:

**Comment by ginalee-dotcom** [comment]
Hi @TerriblyVexed, so does your input only contain `<title>Allergies and Intolerances Section (entries optional)</title> No known allergies. Author (date):Patricia Primary, MD (10/15/2016)` as the information that should show in AllergyIntolerance resource? You might want to try customizing the [provided default template](https://github.com/microsoft/FHIR-Converter/blob/handlebars/src/templates/cda/Sections/Allergies_and_Adverse_Reactions.hbs) for the resource type, as it is written for the matching sample data. 

Also, not sure if it's just on my end but the formatting of your messages is a little bit confusing. Is the last chunk of the message displayed in the box your complete input message?

**Comment by TerriblyVexed** [comment]
I updated the issue with a file b/c the code section isn't working.

**Comment by irenepjoseph** [comment]
Hi, if issue still persists, have you reviewed the default templates [AllergyIntolerance.hbs](https://github.com/microsoft/FHIR-Converter/blob/handlebars/src/templates/cda/Resources/AllergyIntolerance.hbs) and [Medication.hbs](https://github.com/microsoft/FHIR-Converter/blob/handlebars/src/templates/cda/Resources/Medication.hbs) if further customization is needed?
