### ISSUE TITLE
Assessment Data In CCD not converted into FHIR

### ISSUE THREAD

**Issue by SuprakashMaity** [microsoft/FHIR-Converter#348]
Hi Team,

I am trying to convert CCD to FHIR using fhir-converter, but not find the CCD assessment data into FHIR resource. Please help me for the same. Sample Data is given bollow:

<component>
				<section>
					<templateId root="2.16.840.1.113883.10.20.22.2.8"/>
					<id root="b3783f1a-fb34-4e20-9203-02e6c76b9b81"/>
					<code code="51848-0" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Assessment"/>
					<title>Assessment</title>
					<text>
						<table>
							<thead>
								<tr>
									<th>Encounter Date</th>
									<th>Assessment Date</th>
									<th>Assessment</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td styleCode="Botrule">08/24/2021</td>
									<td styleCode="Botrule">08/24/2021</td>
									<td styleCode="Botrule">
										Cardiogram on 5/12/2016 LV function is normal mitral valve mild mitral regurgitation mild tricuspid vegetation RVSP is 42 m mercury and the report
										<br/>
										Insert TEE
										<br/>
										<br/>
										<br/>
										Risk and benefits of TEE, explained to patient, including but not limited to infection, bleeding, arrythmias, disection requiring urgent surgery, MI, CVA or even death and after explaining this to patient, they understood and wish to proceed.
									</td>
								</tr>
							</tbody>
						</table>
						<content>Patient Targets</content>
						<table>
							<thead>
								<tr>
									<th>Encounter Date</th>
									<th>Instructions</th>
									<th>Goals</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td styleCode="Botrule">08/24/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">08/24/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">08/20/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">06/22/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">06/22/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">03/05/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">03/01/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">02/04/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">02/02/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">01/28/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">01/21/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">01/21/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">01/19/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">01/12/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">01/07/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">01/05/2021</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">12/21/2020</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">12/17/2020</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">12/10/2020</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">12/03/2020</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">11/23/2020</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">04/29/2020</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
								<tr>
									<td styleCode="Botrule">03/11/2020</td>
									<td styleCode="Botrule"/>
									<td styleCode="Botrule"/>
								</tr>
							</tbody>
						</table>
					</text>
				</section>
			</component>

Thanks & Regards
Suprakash Maity

**Comment by ginalee-dotcom** [comment]
Hi @SuprakashMaity, we do not have a mapping in place for CCD assessment and plan section, you can see the full list of sections we have mapped [here](https://github.com/microsoft/FHIR-Converter/tree/main/data/Templates/Ccda/Section). You might need to write a mapping for the section yourself, feel free to use any of our default templates for C-CDA as a starting guide. Thanks!
