### ISSUE TITLE
Not able to create Microsoft.Health.Fhir.Liquid.Converter.Tool.exe executable from the code

### ISSUE THREAD

**Issue by manaschandanroy** [microsoft/FHIR-Converter#350]
Please guide as to how can we built the code into this exe. All the folders inside src has to be built or only this specific folder "Microsoft.Health.Fhir.Liquid.Converter.Tool".

Awaiting response !!!!!

**Comment by BoyaWu10** [comment]
Hi @manaschandanroy, if you want to build the solution, you can just set "Microsoft.Health.Fhir.Liquid.Converter.Tool" as the start project and build it directly by Visual Studio 2019. By the way, you can directly download the exe in GitHub [releases](https://github.com/microsoft/FHIR-Converter/releases).
