### ISSUE TITLE
What do you use to keep your liquid templates formatted?

### ISSUE THREAD

**Issue by sam-hoffman** [microsoft/FHIR-Converter#355]
I am doing something similar using liquid templates that will become FHIR JSON, and am finding that it's hard to keep them nicely formatted. Is there a VSCode extension that will work for this type of file?

**Comment by yankunhuang-pku** [comment]
We used to edit manually to keep the correct format. However, I can recommend you to use some VS Code extensions which also support syntax highlighting, formatting and snippet support for the liquid template, such as `Liquid`, `Liquid Language Support`. Hope these extensions can help you~

**Comment by sam-hoffman** [comment]
I found that the Liquid extension added extra tabs to the left of stuff so it migrated to the right across the page :( did you have this issue?

**Comment by yankunhuang-pku** [comment]
Sorry, this is beyond our scope. We edited the templates manually, so we didn't encounter this issue. I think you can consult the person in charge of the Liquid extension.

**Comment by ranvijaykumar** [comment]
> I found that the Liquid extension added extra tabs to the left of stuff so it migrated to the right across the page :( did you have this issue?

@ginalee-dotcom

**Comment by ginalee-dotcom** [comment]
Hi @sam-hoffman, as Yankun suggested above, I'd recommend trying out different VS Code extensions for Liquid that are available, such as `Shopify Liquid` by Shopify. Unfortunately we cannot help with your questions on such extensions, as we are not the owners or developers of those extensions. If you have any questions on using our VS Code extension for FHIR Converter specifically, we can always answer those - let us know!
