### ISSUE TITLE
Having trouble compiling the project in Mac OS

### ISSUE THREAD

**Issue by jmarti326** [microsoft/FHIR-Converter#392]
I would like to know if I need a special instruction for the solution to compile in MacOS.  I want to compile and run the build locally but it seems the solution is Windows dependent.

**Comment by yankunhuang-pku** [comment]
Can you give him some help? @sowu880

**Comment by sowu880** [comment]
The tool is cross platform, you can use `dotnet [command]` in mac terminal or run it on visual studio (MacOS).
If still meet issue, you can upload more details about your running environment, command line and error screen snapshot for more help. @jmarti326

**Comment by irenepjoseph** [comment]
@jmarti326 did feedback provided work for you? If not, you can provide additional details from previous comment.
