### ISSUE TITLE
HL7v2 message validation library 

### ISSUE THREAD

**Issue by dattachandan** [microsoft/FHIR-Converter#393]
Hi MS Healthcare Cloud team, Thanks for the good work and sharing the converter code as OSS. 

I am trying some localised AU/NZ v2 messages to convert to FHIR JSON, and was looking for someone to share their experience with v2 data validation. Can the HL7v2 to FHIR converter also flag validation errors in the HL7v2 messages or is it something the user of the tool must implement separately? If so, is there a separate validation service in the Azure FHIR server for v2 inputs or should I generate a conformance profile using the Messaging Workbench ([MWB](https://www.oit.va.gov/Services/TRM/ToolPage.aspx?tid=253))  and use other OSS libraries such as [HAPI](https://github.com/hapifhir/hapi-hl7v2/blob/master/hapi-testpanel/validation.html)?

**Comment by yankunhuang-pku** [comment]
In this project, we only implemented a simple v2 data validation in [Hl7v2DataValidator.cs](https://github.com/microsoft/FHIR-Converter/blob/7e09d6490e6f4b1057e131312b0725cc634baf8d/src/Microsoft.Health.Fhir.Liquid.Converter/Validators/Hl7v2DataValidator.cs#L13). There is no separate validation service in the Azure FHIR server for v2 inputs for now.

**Comment by dattachandan** [comment]
Thanks @yankunhuang-pku, I can see it's currently a very simple header validator Microsoft.Health.Fhir.Liquid.Converter.Validators. 

> $convert-data endpoint can be used as a component within an ETL pipeline for the conversion of raw healthcare data from legacy formats into FHIR format. 

For the [JSON to FHIR converter](https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/convert-data) is there any CDM template JSON that the team has worked on for the industry accelerators previously for representing [HealthCareService](https://microsoft.github.io/CDM/SchemaViz.html?initialManifest=standards.manifest.cdm.json) in JSON so that we can convert that to FHIR?

**Comment by yankunhuang-pku** [comment]
For JSON to FHIR converter, we provide some sample template in this [folder](https://github.com/microsoft/FHIR-Converter/tree/main/data/Templates/Json). You may need to customize the template according to your needs

**Comment by dattachandan** [comment]
Thanks @yankunhuang-pku. Will give it a try. I will close this ticket
