### ISSUE TITLE
Is there a feature to convert data from legacy formats (such as HL7, CCDA, JSON) to FHIR in bulk?

### ISSUE THREAD

**Issue by sushil-clearsense** [microsoft/FHIR-Converter#396]
Currently, the convert data endpoint only takes one record at a time. Our usecase is to convert the data in bulk (from a database, bulk file containing multiple HL7/CCDA/JSON records)

Is this feature available? or can it be done in any other way?

**Comment by yankunhuang-pku** [comment]
Yes, the endpoint only takes one record at a time now, but you can call the $convert-data endpoint in parallel. 
Another way is to use this tool locally to convert the data in folder:
`>.\Microsoft.Health.Fhir.Liquid.Converter.Tool.exe convert -d myTemplateDirectory -r myRootTemplate -i myInputDataFolder -o myOutputDataFolder`
