### ISSUE TITLE
in the context, I am not seeing the select as template option when i right click a liquid template file

### ISSUE THREAD

**Issue by smdama** [microsoft/FHIR-Converter#398]

**Comment by smdama** [comment]
![image](https://user-images.githubusercontent.com/107129286/172646575-a801319c-800b-435c-95dd-e456aa28ad89.png)

**Comment by yankunhuang-pku** [comment]
@smdama Could you try again by changing the file extension to '.liquid'?

**Comment by irenepjoseph** [comment]
@smdama did the feedback work for you by changing file extension to .liquid ?
