### ISSUE TITLE
Working with GIt from deployed version

### ISSUE THREAD

**Issue by rramosj2** [microsoft/FHIR-Converter#42]
**Is your feature request related to a problem? Please describe.**
Hello, When working with templates and the UI there is a GIT option, that allows us to create, branches, etc. Can we get the URL of the GIT repository where this would be available?
As a user, it would be great to be able to work from the deployed git repository.

**Describe the solution you'd like**
As a user, it would be great to be able to work locally with my editor/file from the deployed git repository.

**Describe alternatives you've considered**
I've deployed locally and worked from there but would like to distribute and collaborate with team members.

**Additional context**

**Comment by deepak-ms** [comment]
Git repo should be at https://<your_fhir_converter_url>/git
It'll need API key, for example,
git -c http.extraheader="X-MS-CONVERSION-API-KEY:<your_api_key>" clone https://<your_fhir_converter_url>/git
