### ISSUE TITLE
OBX Timestamp (TS) values not showing up

### ISSUE THREAD

**Issue by sgtcmofo** [microsoft/FHIR-Converter#426]
Running any hl7 file that has a TS of YYYYMMDD, doesn't return a date.  I've attached a sample hl7 file, oru-r01 liquid template and the json file returned.  Please advise on how we can get these values pulled when using the FHIR Converter.

**HL7 Values**
OBX|5|TS|11368-8^Date of Illness Onset^LN||20210224||||||F
OBX|6|TS|77976-9^Illness End Date^LN||20210302||||||F
OBX|9|TS|77975-1^Diagnosis Date^LN||20210225||||||F
OBX|11|TS|8656-1^Admission Date^LN||20210226||||||F
OBX|12|TS|8649-6^Discharge Date^LN||20210302||||||F
OBX|41|TS|77972-8^Earliest Date reported to county^LN||20210225||||||F
OBX|42|TS|77973-6^Earliest Date reported to State^LN||20210225||||||F

[ORU-R01-01_tsFields.zip](https://github.com/microsoft/FHIR-Converter/files/9401436/ORU-R01-01_tsFields.zip)

Respectfully,
Josh

**Comment by sgtcmofo** [comment]
@evachen96 @ranvijaykumar It seems like none of the TS Fields compute correctly on any of the files provided.  Even if you use a format correct string "20150818060605-0500" it doesn't give a value.  Please advise if this is being looked at or when a fix maybe offered.  We would like to move forward with implement the FHIR API for our project, but this has me concerned.

Respectfully,
Josh

**Comment by sgtcmofo** [comment]
We can close this, I found a spot to add to the Organization template, same place where the DT and DTM happens and just added ST to the if statement.

**Comment by evachen96** [comment]
The conversion templates are based on HL7 v2.8, according to which TS is not a valid value type for OBX.2. Therefore we have not handled TS. Your approach seems correct.
