### ISSUE TITLE
Question: How do I get docker image versions?

### ISSUE THREAD

**Issue by granadacoder** [microsoft/FHIR-Converter#429]
The README from (https://github.com/microsoft/FHIR-Converter) says:

There are other versions released by Microsoft that are stored in a public ACR healthplatformregistry.azurecr.io. 
You can directly pull templates from 
healthplatformregistry.azurecr.io/hl7v2defaulttemplates:`**<version>**` 
without ACR authentication.

So this fails:

`docker pull healthplatformregistry.azurecr.io/hl7v2defaulttemplates:latest
`
with

`
Error response from daemon: manifest for healthplatformregistry.azurecr.io/hl7v2defaulttemplates:latest not found: manifest unknown: manifest tagged by "latest" is not found
`

=====

`
docker pull healthplatformregistry.azurecr.io/hl7v2defaulttemplates
`

`
Using default tag: latest
Error response from daemon: manifest for healthplatformregistry.azurecr.io/hl7v2defaulttemplates:latest not found: manifest unknown: manifest tagged by "latest" is not found
`

======

So I went to the releases folder:

https://github.com/microsoft/FHIR-Converter/releases

and found "[v5.0.4](https://github.com/microsoft/FHIR-Converter/releases/tag/v5.0.4)"

So I tried:

`
docker pull healthplatformregistry.azurecr.io/hl7v2defaulttemplates:v5.0.4
`

`
Error response from daemon: manifest for healthplatformregistry.azurecr.io/hl7v2defaulttemplates:v5.0.4 not found: manifest unknown: manifest tagged by "v5.0.4" is not found
`

and tried this:

`
docker pull healthplatformregistry.azurecr.io/hl7v2defaulttemplates:5.0.4
`

`
Error response from daemon: manifest for healthplatformregistry.azurecr.io/hl7v2defaulttemplates:5.0.4 not found: manifest unknown: manifest tagged by "5.0.4" is not found
`

==================

How do I determine what are valid values for  "`<version>`"  ???

Again quoting:

You can directly pull templates from healthplatformregistry.azurecr.io/hl7v2defaulttemplates:`<version>` without ACR authentication.

Thank you.

**Comment by granadacoder** [comment]
Please help.

**Comment by granadacoder** [comment]
Hi.  I'm still stuck.  Any help would be appreciated.

**Comment by irenepjoseph** [comment]
Hi, thank you for feedback and reporting the issue. I'm following up with engineering team.

**Comment by sowu880** [comment]
Hi, 

`<version>` here is align with major version number (contains one decimal point. e,g, v5.0 or v4.5 

You can try `healthplatformregistry.azurecr.io/hl7v2defaulttemplates:v5.0`.

We will update our doc to list available image list to avoid confusion.

Best,
Songrui

**Comment by irenepjoseph** [comment]
Thank you @sowu880 
Does the resolution work for you @granadacoder?

**Comment by granadacoder** [comment]
it does not "early choke", but does not complete either.

```
docker pull healthplatformregistry.azurecr.io/hl7v2defaulttemplates:v5.0


v5.0: Pulling from hl7v2defaulttemplates
d09ffc980ae5: Pulling fs layer 
invalid rootfs in image configuration
```

**Comment by granadacoder** [comment]
Same thing on a windows machine:

`
c:\work>docker pull healthplatformregistry.azurecr.io/hl7v2defaulttemplates:v5.0


v5.0: Pulling from hl7v2defaulttemplates
d09ffc980ae5: Downloading [=>                                                 ]  15.41kB/471.6kB
invalid rootfs in image configuration

c:\work>



`

**Comment by granadacoder** [comment]
the error

'invalid rootfs in image configuration'

pointed me towards that this library is an OCI image (not a docker image).

` oras pull healthplatformregistry.azurecr.io/hl7v2defaulttemplates:v5.0`

the above command downloaded the below file:

layer1.tar.gz

=================

oras can be installed from here (below link):

https://oras.land/cli/

it is described here (below link):

https://learn.microsoft.com/en-us/azure/container-registry/container-registry-oci-artifacts#pull-an-artifact

**Comment by granadacoder** [comment]
So 'v5.0' is essentially a "magic value".


//start quote

We will update our doc to list available image list to avoid confusion.

Best,
Songrui

//end quote


Yes.  Please.  I think all "magic values" should be documented well.

@sowu880 sowu880 

My question is


is "v5.0" changed/updated when a new release comes out.

Aka, does "v5.0" contain (as of today) the latest version of "v5.0.4" ? 

or does it contain only

https://github.com/microsoft/FHIR-Converter/releases/tag/v5.0.0

?

Thank you.

**Comment by sowu880** [comment]
The image does OCI images, you should use our tool to pull the image (https://github.com/microsoft/FHIR-Converter#using-templates).

Our tool is developed based on Oras, therefore Oras can be used to pull the image without error, but the file is tar.gz file which needs unzip and merge different layers by our tool. The content is incorrect if using docker or Oras.

Sample templates will not change within major version, that is v5.0 templates applied to any v5.0.x versions includes v5.0.4.

**Comment by granadacoder** [comment]
So this call fails:

    oras pull healthplatformregistry.azurecr.io/hl7v2defaulttemplates:v5.1

with message:

    Error: healthplatformregistry.azurecr.io/hl7v2defaulttemplates:v5.1: not found

....

So the 5.1.0 files .. are accessible by

oras pull healthplatformregistry.azurecr.io/hl7v2defaulttemplates:v5.0 

??

I'm still confused.

At what point does the version of the oras call......get incremented?

**Comment by sowu880** [comment]
Hi,
v5.1 has been updated. You can use v5.1 now.

Best.

**Comment by granadacoder** [comment]
For future readers.. here is the predictable way to figure out the magic numbers.


    az acr repository list --name healthplatformregistry.azurecr.io --output table


(COMMENT (it is public, so empty-string is ok for username and pwd if prompted))


    Username: 
    Password: 

(and results below)


```
Result

--------------------------------------

ccdadefaulttemplates
ccdasampledata
fhir-analytics-data-source
fhirconverter
fhirtodatalake
fhirtodatalaketool
growth-chart-app
hardwareinfo
health-paas-codespaces
healthdatatodatalaketool
hl7v2
hl7v2defaulttemplates
hl7v2sampledata
jsondefaulttemplates
jsonsampledata
medications-app
public/healthcareapis/r4-fhir-server
public/healthcareapis/r4b-fhir-server
public/healthcareapis/r5-fhir-server
public/healthcareapis/stu3-fhir-server
r4_fhir-server
r4b_fhir-server
r5_fhir-server
samples/counter-image
stu3_fhir-server
stu3sampledata
stu3tor4defaulttemplates
wordclouddata


```

(pick one of the above for the --repository argument below)

```
az acr repository show-tags --name healthplatformregistry.azurecr.io  --repository ccdadefaulttemplates --orderby time_desc --output table

(and results below)

Result
--------
v5.1
v5.0
v4.5
v4.4
v4.3
v4.1
v4.0
```
