### ISSUE TITLE
CCDA to FHIR conversion issue

### ISSUE THREAD

**Issue by manasaprabala** [microsoft/FHIR-Converter#437]
Hi Team, Currently we have the CCD template available in GitHub. Could you please provide us the CCDA template as well.

We tried converting the CCDA using CCD templates but lot of information was missing from FHIR JSON.

**Comment by hongyh13** [comment]
Hi, we provide some ready-to-use templates as examples. If needed, you can create a new template, or modify existing templates to meet your specific conversion requirements using [Liquid](https://shopify.github.io/liquid/) templating language.
