### ISSUE TITLE
Support of Ubuntu for Microsoft.Health.Fhir.Liquid.Converter.Tool

### ISSUE THREAD

**Issue by VOVELEE** [microsoft/FHIR-Converter#439]
Hello,

is it possible to execute Microsoft.Health.Fhir.Liquid.Converter.Tool under ubuntu?
Is this a supported scenario?

**Comment by sowu880** [comment]
Hi,
For now, we don't support it in ubuntu and may support it in the future.
If you really need the feature, you can folk the project, try to modify implementation in OrasClient.cs and replace Oras file with ubuntu version. There will be not too much effort.
