### ISSUE TITLE
How to convert the data from SQL Server to Azure API For FHIR database.

### ISSUE THREAD

**Issue by Kedar782** [microsoft/FHIR-Converter#448]
I have all of my data present in the SQL Server. I have thousands of patients. I cannot insert my data manually.
Is there any ETL process that can handle the data ingestion process? Our C-CDA does not match the current version.

Has anybody here written any mapper which converts data directly from the SQL server to Azure Cosmos DB for the Azure API For FHIR?

I will really appreciate your help on this. Please let me know if you have any questions for me.

**Comment by moria97** [comment]
Hi @Kedar782 , currently we don't have an ETL process that can copy data from SQL server to Azure API for FHIR. You have to write the ETL pipeline yourself.
