### ISSUE TITLE
Incomplete handling of telephone numbers from XTN fields

### ISSUE THREAD

**Issue by cksavia** [microsoft/FHIR-Converter#462]
### Incomplete handling of telephone numbers from XTN fields
Converter does not handle XTN fields built with HL7 v2.3, v2.3.1, or v2.4 and may not handle all implementations of HL7 v2.5+

#### Current Behavior
Currently, a phone number will be populated in two circumstances:

1. If `XTN.7: Local Number `and `XTN.12: Unformatted Telephone Number` are both null, the `value` is populated by `XTN.1: Telephone Number`.
2. If `XTN.3: Telecommunication Equipment Type` is not `x.400` or `Internet`, the `value` is populated by `XTN.12: Unformatted Telephone Number`.

#### Why This Is Incomplete
1. This works for HL7 v2.1 and v2.2, but only works for v2.3+ if the _optional_ `XTN.7` field and _conditional_ `XTN.12` field are left empty by the sender.
2. This only works if the _conditional_ `XTN.12` field is populated. This field is not present in v2.3, v2.3.1, or v2.4. Furthermore, because `XTN.12` is _conditional_, the sending system may choose not to populate it when the telecom info can be parsed properly.

#### Possible Suggestions

- If `XTN.12.Value` empty, use `XTN.1.Value`
- Construct full telephone number from `XTN.5: Country Code`, `XTN.6: Area/city Code`, `XTN.7: Local Number`, `XTN.8: Extension`

**Comment by evachen96** [comment]
Hi @cksavia , thanks for your submission! These templates are based off HL7 v2.8, other versions will require some customization. However, we've added your suggestion to our backlog for consideration. Thanks!
