### ISSUE TITLE
FHIR converter format issue

### ISSUE THREAD

**Issue by camila8** [microsoft/FHIR-Converter#47]
It is counting PID-3 wrong. I think your CX handle is not right.
![fhir converter broken](https://user-images.githubusercontent.com/23110570/87987692-a7fc5280-caa4-11ea-8fc6-b6effa4285b4.png)

**Comment by camila8** [comment]
I took out the format in cx and xn and i think the parsing is wrong because now we are getting this error:
It complains with this error now:
```{    "error": {        "code": "BadRequest",        "message": "Unable to parse input data. The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined"    }}

**Comment by ranvijaykumar** [comment]
Thanks for reporting the issue. The template was not handling repeated values inside PID-3 properly. Now it is fixed.

**Comment by camila8** [comment]
Something is still off. Its better but the first MRN has coding system of MR and it should have populated in FHIR.
![image](https://user-images.githubusercontent.com/23110570/88555233-25681b80-cfed-11ea-99ac-c70766fd3f12.png)

**Comment by camila8** [comment]
Thanks!

**Comment by camila8** [comment]
I am seeing the same issue for PID-13. Your example messages doesn't have repeating but in Epic they do. I am going to update using your change but just thought you should know.
![image](https://user-images.githubusercontent.com/23110570/88556414-9d831100-cfee-11ea-81e7-a3fe96e357b9.png)
