### ISSUE TITLE
explain use of uuid 

### ISSUE THREAD

**Issue by rramosj2** [microsoft/FHIR-Converter#48]
**Is your feature request related to a problem? Please describe.**
I am using FHIR Converter successfully but would also like to create a separate application that need to create the same UUID/GUID as in the converter.
When I rung uuid v3 "XXXXXX" URL from the command line the results I get are not the same as the converter does through the API.
For example, 
uuid v3 MTAwMDY1NzlNUg== URL produces 5bd1496a-f235-3d0f-ad43-685b7bab5a08
but the HL7 message produces: "fullUrl": "urn:uuid:64bac34e-e611-3549-848b-89416176aa0b",

**Describe the solution you'd like**
What should the correct call to uuid be to produce the same UUID

**Describe alternatives you've considered**
We've created a template that outputs the UUID as required but this could be a bit simpler.
From the code this is how the UUID is created. do you have any further details?
return uuidv3(''.concat(urlNamespace), uuidv3.URL);**Additional context**

**Comment by deepak-ms** [comment]
@rramosj2, I couldn't repro the issue. I tried following template and got the id same as in cmdline invocation. Am I missing anything?

```
{
    "id":"{{generateUUID 'MTAwMDY1NzlNUg=='}}"
}
```

output:
```
{
  "id": "5bd1496a-f235-3d0f-ad43-685b7bab5a08"
}
```
