### ISSUE TITLE
How do I build the code?

### ISSUE THREAD

**Issue by ashishb** [microsoft/FHIR-Converter#482]
Any command-line interface (CLI) instructions that I can follow to build this code?

**Comment by ms-teli** [comment]
Hi, you can build the project just like a regular c# project with ```dotnet``` on this file: ```./src/Microsoft.Health.Fhir.Liquid.Converter.Tool/Microsoft.Health.Fhir.Liquid.Converter.Tool.csproj```

The artifacts will be located in the bin output folder.

You can also use Visual Studio or any other IDE to work with this solution file: ```./Fhir.Liquid.Converter.sln```
