### ISSUE TITLE
Swagger Doc incorrect for Convert functionality

### ISSUE THREAD

**Issue by mikemassa84** [microsoft/FHIR-Converter#50]
**Describe the bug**
The swagger doc for the convert api has an incorrect url. The doc shows this:
/api/convert/{template}

The actual url is this:
/api/convert/hl7v2/{template}

**To Reproduce**
1. Navigate to *converterurl*/api-docs/#/
2. Scroll to /api/convert/{template}
3. Notice it is incorrect
4. Attempt to send a post request with an hl7v2 message to that endpiont
5. Notice http 502 error
6. Send a post request to updated uri: /api/convert/hl7v2/*{template}*
7. Notice http 200 success

**Expected behavior**
Swagger doc should accurately reflect api

**Screenshots**
Problem:
![image](https://user-images.githubusercontent.com/14846033/88406853-dcb72500-cd96-11ea-9ed7-97368f0ea7f9.png)

Does not match:
![image](https://user-images.githubusercontent.com/14846033/88406895-ea6caa80-cd96-11ea-820d-f1070bee09f9.png)

**Browser:**
n/a

**Additional context**
Recent update to the converter changed the URI from hl7 to hl7v2, and swagger documentation did not reflect this.

**Comment by ranvijaykumar** [comment]
The {template} names itself contains  'hl7v2/' or 'cda/' prefixes.  For example, 'cda/ccd.hbs' and 'hl7v2/ADT_A01.hbs'. You can get the list of template names using the GET /api/templates.
