### ISSUE TITLE
How to use FHIR-Converter?

### ISSUE THREAD

**Issue by kedarnath782** [microsoft/FHIR-Converter#511]
I have Azure Api For FHIR. On top of it I have added Microsoft FHIR Proxy to pass the ONC G10 certification. (I added SMART on my AZure API for FHIR)

I have all my data in SQL server. I want to ingest all my data into AZure API for FHIR. Can I use this solution for it? If yes, can you please guide me with this. I'm sorry I'm very new to this.
Also, I need to do reverse migration means ingesting data from Azure API for FHIR to Sql Server.

How can I do this? I will really appreciate your help on this. I'm stuck on it.

**Comment by dustinburson** [comment]
@kedarnath782 Thank you for your interest in FHIR-Converter.  If you have data in an arbitrary structure in SQL, you could use convert to help import the data into FHIR.  The main impediment is you have a non-standard format.  Out of the box we have support for HL7v2, CCDA, and FHIR STU3 to R4.  We also support JSON as source, so if you are willing to export your SQL data as JSON, you could make a custom template that then would allow you to use $convert and transform the JSON to valid FHIR resources.  Depending on your SQL server, many of them support generating JSON from SQL data. See https://learn.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver16&tabs=json-path as one example.

You can learn more here for the managed service $convert-data operation here https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/overview-of-convert-data.
