### ISSUE TITLE
Converting FHIR to HL7

### ISSUE THREAD

**Issue by EthelEz** [microsoft/FHIR-Converter#522]
Hello Microsoft,

Is it possible to convert the FHIR Bundle or individual Resources to HL7 messages using this converter?

Regards,
Eze

**Comment by ShaunDonn2** [comment]
Hi Eze, yes, you can use the [JsonToHl7v2Processor](https://github.com/microsoft/FHIR-Converter/blob/2f25215f60fa7fdcf8a0595d5d539dd20425aeda/src/Microsoft.Health.Fhir.Liquid.Converter/Processors/JsonToHl7v2Processor.cs#L26) to convert FHIR to Hl7v2.

**Comment by EthelEz** [comment]
Oh, awesome! I wasn't able to find example usages, which was why I asked. 
Please, have you by any chance used it? If yes, can you share?

In the meantime, I will keep trying how to implement it, but will appreciate your response.

Thank you!
