### ISSUE TITLE
 PID-13 not repeatable

### ISSUE THREAD

**Issue by camila8** [microsoft/FHIR-Converter#53]
I am seeing the same issue for PID-13. Your example messages doesn't have repeating but in Epic they do. I am going to update using your change but just thought you should know.
![image](https://user-images.githubusercontent.com/23110570/88556414-9d831100-cfee-11ea-81e7-a3fe96e357b9.png)

_Originally posted by @camila8 in https://github.com/microsoft/FHIR-Converter/issues/47#issuecomment-664443578_

**Comment by ranvijaykumar** [comment]
Thanks for raising the issue. It has been fixed in the commit ed99dcf
