### ISSUE TITLE
External contributions

### ISSUE THREAD

**Issue by MarceloLaser** [microsoft/FHIR-Converter#530]
Hello, I'm wondering if this project's documentation is up to date, given that the last release and documentation update was two years ago. Also, I'd like to know whether this project accepts contributions from people external to Microsoft.

**Comment by wi-y** [comment]
@MarceloLaser yes the documentation should be up to date. The core convert engine hasn't really changed much since the project was first released and most of the heavy lifting is done by the liquid templates. This project accepts external contributions
