### ISSUE TITLE
Provide documentation for the expected structure of a template container

### ISSUE THREAD

**Issue by liammoat** [microsoft/FHIR-Converter#560]
The `fhir-converter` service has support for using Azure Storage as a custom template library. 

However, to my knowledge, we do not provide documentation for the structure of the storage container.  For example, should we upload raw `.liquid` files, should they be archived in a `.tar.gz` or something else?

**Comment by ShaunDonn2** [comment]
Thanks @liammoat for the feedback. Looking into this.

**Comment by leonidaxx90** [comment]
I'm trying to use custom template but when perform this POST request:

`{
      "InputDataFormat": "Hl7v2",
      "RootTemplateName": "Hl7v2/ADT_A01",
      "InputDataString": "MSH|^~\\&|SIMHOSP|SFAC|RAPP|RFAC|20200508131015||ADT^A01|517|T|2.3|||AL||44|ASCII\nEVN|A01|20200508131015|||C005^Whittingham^Sylvia^^^Dr^^^DRNBR^PRSNL^^^ORGDR|\nPID|1|3735064194^^^SIMULATOR MRN^MRN|3735064194^^^SIMULATOR MRN^MRN~2021051528^^^NHSNBR^NHSNMBR||"
  }`

I receive:

`{
    "error": {
        "code": "InvalidTemplate",
        "message": "The template content or name is invalid.",
        "innerError": {
            "code": "TemplateNotFound",
            "message": "The requested template could not be found: Template 'Hl7v2/ADT_A01' not found"
        }
    }
}`

In attach a visual organization of the liquid template in the container.

Thanks
<img width="704" alt="Screenshot 2024-09-25 at 00 41 31" src="https://github.com/user-attachments/assets/c77b5df6-d808-41fb-abdc-95d578e2cf10">
<img width="516" alt="Screenshot 2024-09-25 at 00 41 24" src="https://github.com/user-attachments/assets/e1ced051-2244-404a-a748-6797bc533dba">
