### ISSUE TITLE
FHIR converter Service - CCD to FHIR conversion - getting response message like Input data size: 182743B exceeds limit: 102400B.

### ISSUE THREAD

**Issue by Sathishsanro** [microsoft/FHIR-Converter#564]
When we process the entire CCD file to FHIR conversion using fhir-converter service, we are getting the response message like **Input data size: 182743B exceeds limit: 102400B.** This issue can reproduce using sample ccda "Transfer_Summary.ccda" file. 

Please let me know any settings to process the entire CCD file in fhir-converter service.

FYI,

**Response:**

{
    "error": {
        "code": "InvalidRequestBody",
        "message": "An error was found while validating the request body.",
        "innerError": {
            "code": "InvalidInputDataRequestValue",
            "message": **"Input data size: 182743B exceeds limit: 102400B."**
        }
    }
}

**Comment by rogordon01** [comment]
Hello @Sathishsanro . Thanks for bringing this to our attention. The [MCR Container Image](https://mcr.microsoft.com/en-us/product/healthcareapis/fhir-converter/tags) includes request filtering that prevents input data larger than 100kb. Unfortunately this prevents the use of some sample data, as you've discovered. We are making changes on our end to increase this limit and roll it out in our next released image. I will update this thread when that occurs.

In the meantime please make use of any data underneath the 100k limit.

**Comment by rogordon01** [comment]
@Sathishsanro a new image has been released with the increase in the data size limit. This supports all sample data within our repo, so you should no longer have any issues. I've attached the relevant image tag below. 

`mcr.microsoft.com/healthcareapis/fhir-converter:1.0.8-preview`
https://mcr.microsoft.com/en-us/product/healthcareapis/fhir-converter/tags

**Comment by sanket-t-shah** [comment]
@rogordon01 - am facing this issue again on MCR Version: fhir-converter:1.0.229-preview and above.

Please see the screenshot below. What's the possible fix here to keep the files of flexible size?

<img width="1089" height="250" alt="Image" src="https://github.com/user-attachments/assets/d2a4bbf6-b51e-4251-9df3-f2156a2fe435" />

**Comment by dustinburson** [comment]
Hello @sanket-t-shah can you provide details on the template and why it is so large? The orginal increase was from 100 KB to 500 KB.

**Comment by sanket-t-shah** [comment]
@dustinburson - This is not template, but input file. We are receiving files up to 1 MB size from CommonWell QHIN. Can you please help to provide an upper size limit as configurable value instead of hard-coded? That's a bit of a surprise as the original code seems not to be in sync with MCR Image and seeing hard-coded values in code doesn't look very convincing.
