### ISSUE TITLE
Only Patient resource is in bundle V2 converter

### ISSUE THREAD

**Issue by camila8** [microsoft/FHIR-Converter#57]
**Describe the bug**
I think PID fix broke the other resources. I only see the Patient resource in the FHIR bundle. I no longer see the encounter and procedure ones and others.

**To Reproduce**
1. Go to FHIR Converter
2. Load A01.hbs template and any ADT message
3. Scroll down to FHIR bundle
4. See only patient resource 

**Expected behavior**
I expect to see many other FHIR resources in the bundle

**Screenshots**
![image](https://user-images.githubusercontent.com/23110570/88713935-adc7e880-d0e1-11ea-82b2-892445013215.png)

**Comment by camila8** [comment]
If you move line 7 to line 12 it temp fixes it.
![image](https://user-images.githubusercontent.com/23110570/88716250-698a1780-d0e4-11ea-81ee-57aa941f7f36.png)


![image](https://user-images.githubusercontent.com/23110570/88716190-51b29380-d0e4-11ea-980c-7e1e82860383.png)

**Comment by ranvijaykumar** [comment]
I am unable to repro the issue. Please compare your templates with the version in github to ensure those are not inadvertently changed.

**Comment by camila8** [comment]
there was an extra }, at the end of my patient.hbs
