### ISSUE TITLE
"path" parameter error when running locally

### ISSUE THREAD

**Issue by coldn00dles** [microsoft/FHIR-Converter#571]
I am trying to build the FHIR convertor tool csproj file via visual studio 22. After figuring out the command line arguments for the "convert" method, i gave the appropiate inputs and outputs in the debug command line arguments, for instance these : 
`convert --TemplateDirectory "data\Templates\Ccda" --RootTemplate "DischargeSummary" --InputDataFile "sampleccda.ccda" --OutputDataFile "output.json"`  

However, I am getting an error when building upon this. 
`Process failed: Path cannot be the empty string or all whitespace. (Parameter 'path')`

Path isnt exactly an argument within the convert method(it results in another error), so how am I supposed to navigate this? Apologies in advance I have almost nil experience in .NET and am just trying to run the project

**Comment by pallar-ms** [comment]
@coldn00dles, I think the issue could be because the InputDataFile needs to include the absolute path to the input file.
Refer example in this link - https://github.com/microsoft/FHIR-Converter/tree/e49b56f165e5607726063c681e90a28e68e39133?tab=readme-ov-file#converting-individual-files
