### ISSUE TITLE
Customizing Deployment to use separate Github Repo

### ISSUE THREAD

**Issue by rramosj2** [microsoft/FHIR-Converter#59]
**Is your feature request related to a problem? Please describe.**
when setting up a custom deployment of the FHIR Converter. We need to specify the Docker Registry - username and password.
Can you describe how to set those up?

**Describe the solution you'd like**
Instructions to connect to the Docker Registry repository

**Describe alternatives you've considered**
I have set up a pipeline both from Github Action and from Azure App Services the build works but the Docker image fails as it needs user/password.

**Additional context**

**Comment by deepak-ms** [comment]
Not sure if I fully understand the issue here. Does [this](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) help?

**Comment by rramosj2** [comment]
Thanks Deepak,
I did figure it out that the container image needs to come out from our own
repository.
I have a second question. I can open a ticket if needed.
Do you have any suggestions as to if it would be possible to use blob
storage as the file reference for the converter app's template files?

*Renzo Ramos*

Senior Consultant

M: 717 620 9092

rramos@j2interactive.com



*J2 Interactive*

www.j2interactive.com

**Comment by deepak-ms** [comment]
Azure file storage should work in a seamless manner after [mounting](https://docs.microsoft.com/en-us/azure/app-service/containers/how-to-serve-content-from-azure-storage), while blob storage might need some adapter.
