### ISSUE TITLE
Web UI and API return different json response

### ISSUE THREAD

**Issue by mikemassa84** [microsoft/FHIR-Converter#60]
**Describe the bug**
The json response displayed in the Web UI contains a different bundle than the json response returned by the API for the same HL7v2 message. This can be confusing for users. The Web UI returns only the fhir bundle while the api returns the fhir bundle along with an invalidAccess object and an unusedSegments object.

**To Reproduce**
1. Go to the Web UI
2. Make sure HL7v2 is selected
3. Select ADT_A01.hbs from the template drop down.
4. Paste in an ADT message to convert in the top frame
5. Notice the bottom right frame contains only the converted fhir bundle
6. Send a POST request to /api/convert/hl7v2/ADT_A01.hbs with the same ADT message from step 4.
7. Notice the json response contains elements named "unusedSegments", "invalidAccess", and "fhirResource". This is different from the output of step 5.

**Expected behavior**
The response from the Web UI and the api should match.

**Screenshots**
Input and output are attached.

**Browser:**
Chrome

**Additional context**

[adt.txt](https://github.com/microsoft/FHIR-Converter/files/5042694/adt.txt)
[api_response.txt](https://github.com/microsoft/FHIR-Converter/files/5042695/api_response.txt)
[webui_response.txt](https://github.com/microsoft/FHIR-Converter/files/5042696/webui_response.txt)

**Comment by ranvijaykumar** [comment]
The invalidAccess object and the unusedSegments are used by the UI for rendering purpose. We can take additional parameters to suppress those objects as those may not be useful in a pipeline. Would that work for you?

**Comment by mikemassa84** [comment]
> The invalidAccess object and the unusedSegments are used by the UI for rendering purpose. We can take additional parameters to suppress those objects as those may not be useful in a pipeline. Would that work for you?

Yes, that would work for us.

**Comment by ACMoretxj** [comment]
Close this issue, feel free to reactivate it for any questions.
