### ISSUE TITLE
convertMessage is not defined

### ISSUE THREAD

**Issue by pjirsa** [microsoft/FHIR-Converter#69]
https://github.com/microsoft/FHIR-Converter/blob/2fcca8c2750b46394718e867bb97f3b9a84b20a7/src/static/js/template-editor.js#L524

Console is displaying `convertMessage is not defined` error when clicking Refresh button in web UI

**Comment by ranvijaykumar** [comment]
@Patrick2011 FYI

**Comment by ACMoretxj** [comment]
Thanks @pjirsa for the feedback. The reason is that the `convertMessage` is a previous name for `convertData`.
The issues has been solved on branch `personal/xiatia/fix-issue-#69`, and will be merged into `master` soon.
Please feel free to explore more and make suggestions :)
