### ISSUE TITLE
Bug while processing German umlaut letters Ä, ä ,Ö, ö ,Ü, ü, ß  in HL7v2 message

### ISSUE THREAD

**Issue by sandeep59** [microsoft/FHIR-Converter#78]
Hi,
I have came across a bug in FHIR converter tool while converting an HL7 v2 message containing German umlaut symbols  Ä, ä ,Ö, ö ,Ü, ü, ß  into FHIR resource.

Tool is removing above mentioned letters from the message string. In the below image we are getting Tübingen as the city in HL7 v2 message and while converting the segment data into fhir resource, ü is removed and output looks like Tbingen.
Please refer the below snapshots- 
Note:-This is an anonymized message with fake patient name and address

<img width="877" alt="Capture" src="https://user-images.githubusercontent.com/16953074/95474777-d1cb6400-0985-11eb-83e0-fa6759c0af73.PNG">
<img width="189" alt="Capture1" src="https://user-images.githubusercontent.com/16953074/95475098-2d95ed00-0986-11eb-8366-54ef93f95a7b.PNG">

Thanks

**Comment by ACMoretxj** [comment]
Thanks for your feedback. Actually the editor can not process the utf8 input appropriately. Currently it has been solved.
