### ISSUE TITLE
getting error when invoking API to convert - "The first argument must be one of type string, Buffer,

### ISSUE THREAD

**Issue by vbhatt1959** [microsoft/FHIR-Converter#81]
{
  "error": {
    "code": "BadRequest",
    "message": "Unable to parse input data. The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined"
  }

**Comment by vbhatt1959** [comment]
curl -X POST "http://localhost:2019/api/convert/hl7v2%2FADT_A01.hbs" -H "accept: application/json" -H "Content-Type: text/plain" -d "MSH|^~\\&|WebOMR^2.16.840.1.113883.3.186^ISO|BIDMC^2.16.840.1.113883.3.186^ISO|BBC_HIE^^ISO|^^ISO|20190329053443-0400||ORU^R01^ORU_R01|BIDMC_17992605|P|2.5.1|||NE|NE|||||PHLabReport-NoAck^^2.16.840.1.114222.4.10.3^ISOSFT|CCC^D^^^^BIDMC&2.16.840.1.113883.3.186&ISO^XX^^^2.16.840.1.113883.3.186|1|BIDMC Lab Systems|1||19780101PID|1||XYZ22190101^^^BIDMC&2.16.840.1.113883.3.186.2&ISO^SN~43150901 7^^^BIDMC&2.16.840.1.113883.3.186.2&ISO^VN||MENHION^DODID||19540930|M||2106-3^Black^HL70005|69 JOHNSON ST^^TAUNTON^MA^02780^USA^H||^PRN^PH^^1^508^8848775||en-US^^PHVS_Language_ISO_639-2_Alpha3|M^^HL70002||||||UNKNOW||||||||NORC|RE|1828517.1^EHR^2.16.840.1.113883.19.3.2.3^ISO|1828517.1^EHR^2.16.840.1.113883.19.3.2.3^ISO|||||||||1548202641^^Bidmc^^^^^^NPI&2.16.840.1.113883.4.6&ISO|||||||||BIDMC^L^^^^OID&2.16.840.1.113883.19.4.6&ISO^XX^^^2.16.840.1.113883.3.186|330 Brookline Avenue^^Boston^MA^02215^USA^B|^PRN^PH^^1^617^6677000OBR|1||1828517.1.1^EHR^2.16.840.1.113883.19.3.2.3^ISO|600-7^Bacteria identified in Blood by Culture^LN^307^Blood Culture, Routine^99USI|||201903290236-0400|201903290236-0400|||||\"None\"|||1548202641^^Bidmc^^^^^^NPI&2.16.840.1.113883.4.6&ISO||||||201903290520-0400||MB|X||||||SPM|1|1828517.1&EHR&2.16.840.1.113883.19.3.2.3&ISO^1828517.1&EHR&2.16.840.1.113883.19.3.2.3&ISO||BLDV^Blood venous^HL70070^BLC^BLOOD CULTURE^99USI^20080131^2.5.1"

**Comment by ACMoretxj** [comment]
The request url `http://localhost:2019/api/convert/hl7v2%2FADT_A01.hbs` doesn't work for me too. I noticed the `%2F` is actually the result of `encodeURIComponent('/')` and I guess you actually want to use `http://localhost:2019/api/convert/hl7v2/ADT_A01.hbs` as request url, how about trying to use it instead of the previous one?

**Comment by vbhatt1959** [comment]
I can control replacing "hl7v2%2FADT_A01.hbs" with"hl7v2/ADT_A01.hbs" if i am running curl from the command line however the issue is when running from Swagger using the the FHIR Converter API.

**Comment by ACMoretxj** [comment]
In the master branch, I have tried to use Swagger portal to run this API, the following is the parameters:

![1](https://user-images.githubusercontent.com/9417900/96087804-06e03500-0ef7-11eb-88c0-b72cb50b9a3d.png)

And I got the response data as follows:

![2](https://user-images.githubusercontent.com/9417900/96087836-1495ba80-0ef7-11eb-92ba-41c8c2f000ed.png)

The result seems to be correct, can you give me some screenshots about your swagger portal?

**Comment by ACMoretxj** [comment]
Close this issue, feel free to reopen it for any questions.
