### ISSUE TITLE
Swagger header for `api/templates` PUT is incorrect

### ISSUE THREAD

**Issue by ewoutkramer** [microsoft/FHIR-Converter#88]
**Describe the bug**
The `file` parameter misses a `type`, and the `name` (body) parameter should have a `schema`.

**To Reproduce**
1. Get the api-docs.json file 
2. Upload it to a validator (like swaggerhub.com)
3. The validator highlights these errors

**Additional context**
I discovered this while trying to convert the swagger output to a C# server stub - using swaggerhub.com.  The generator complained. After some research I found the swagger file generated by the converter API is incorrect.

I'll send a PR to fix it.

**Comment by ACMoretxj** [comment]
Thank you Ewout for helping us refining the documentation quality : )
