### ISSUE TITLE
Error in Accessing HL7 v2 field information

### ISSUE THREAD

**Issue by sandeep59** [microsoft/FHIR-Converter#90]
Hi,
I have customized the ADT templates as per the version of HL7 v2, I could access the information from a field  PV1-2 earlier and after few days I again run the templates but this time the information from PV1-2 is not accessible, then I used PV1-2-1 to access the same information in partial templates, and now this doesn't work any more, I have to use PV1-2-1-1 to access the same information.

It seems that this is happening after I configured for subcomponents for HL7 v2 in few fields but not sure.

Note:- PV1 segment is an example

<img width="852" alt="Capture" src="https://user-images.githubusercontent.com/16953074/97147120-49143c80-1769-11eb-91dc-11ecce6477cc.PNG">
<img width="830" alt="Capture2" src="https://user-images.githubusercontent.com/16953074/97147244-7d87f880-1769-11eb-947b-70faaef3c39f.PNG">

**Comment by ACMoretxj** [comment]
Sorry for can't understand your issue, could you please descript your issue with more details?

**Comment by sandeep59** [comment]
> Sorry for can't understand your issue, could you please descript your issue with more details?

I have updated the comments.

**Comment by ACMoretxj** [comment]
Can you provide the templates and sample data you used in this scenario?

**Comment by sandeep59** [comment]
> Can you provide the templates and sample data you used in this scenario? (Of course please desensitize sensitive data)

Template used is ADT_A01 it is being customized as per our requirements.

MSH|^~\&|AccMgr|1|||20050110045504||ADT^A01|599102|P|2.3||| 
EVN|A01|20050110045502||||| 
PID|1||10006579^^^1^MR^1||DUCK^DONALD^D||19241010|M||1|111 DUCK ST^^FOWL^CA^999990000^^M|1|8885551212|8885551212|1|2||40007716^^^AccMgr^VN^1|123121234|||||||||||NO 
NK1|1|DUCK^HUEY|SO|3583 DUCK RD^^FOWL^CA^999990000|8885552222||Y|||||||||||||| 
PV1|1|I|PREOP^101^1^1^^^S|3|||37^DISNEY^WALT^^^^^^AccMgr^^^^CI|||01||||1|||37^DISNEY^WALT^^^^^^AccMgr^^^^CI|2|40007716^^^AccMgr^VN|4|||||||||||||||||||1||G|||20050110045253|||||| 
GT1|1|8291|DUCK^DONALD^D||111^DUCK ST^^FOWL^CA^999990000|8885551212||19241010|M||1|123121234||||#Cartoon Ducks Inc|111^DUCK ST^^FOWL^CA^999990000|8885551212||PT| 
DG1|1|I9|71596^OSTEOARTHROS NOS-L/LEG ^I9|OSTEOARTHROS NOS-L/LEG ||A| 
IN1|1|MEDICARE|3|MEDICARE|||||||Cartoon Ducks Inc|19891001|||4|DUCK^DONALD^D|1|19241010|111^DUCK ST^^FOWL^CA^999990000|||||||||||||||||123121234A||||||PT|M|111 DUCK ST^^FOWL^CA^999990000|||||8291 
IN2|1||123121234|Cartoon Ducks Inc|||123121234A|||||||||||||||||||||||||||||||||||||||||||||||||||||||||8885551212 
IN1|2|NON-PRIMARY|9|MEDICAL MUTUAL CALIF.|PO BOX 94776^^HOLLYWOOD^CA^441414776||8003621279|PUBSUMB|||Cartoon Ducks Inc||||7|DUCK^DONALD^D|1|19241010|111 DUCK ST^^FOWL^CA^999990000|||||||||||||||||056269770||||||PT|M|111^DUCK ST^^FOWL^CA^999990000|||||8291 
IN2|2||123121234|Cartoon Ducks Inc||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||8885551212 
IN1|3|SELF PAY|1|SELF PAY|||||||||||5||1

**Comment by ACMoretxj** [comment]
Hi, after parsing the data you provided, the result points that the content of `PV1-2` is as follows:

```json
[
    [
        "1"
    ]
]
```

Apparantly the `PV1-2`, `PV1-2-1` and `PV1-2-1-1` are all equal to `'I'` (`[['I']] == 'I'` will return `true` in node). This can explain why you can one side change the identifier and one side still get a workable result.

On the other hand, if you changes the sample data or something else which causes the `PV1-2` becoming more complex than a single `[['I']]`, the condition will no longer be true.

Hope it helps for you, if I missed anything, please feel free to point out.

**Comment by sandeep59** [comment]
Can you please explain by utilizing some hl7 v2 message, how does it change by changing data in message?

**Comment by ACMoretxj** [comment]
Sure. Replace the PV1 line in the data you provided with the following one:

```text
PV1|1|I^text|PREOP^101^1^1^^^S|3|||37^DISNEY^WALT^^^^^^AccMgr^^^^CI|||01||||1|||37^DISNEY^WALT^^^^^^AccMgr^^^^CI|2|40007716^^^AccMgr^VN|4|||||||||||||||||||1||G|||20050110045253|||||| 
```

And the `PV1-2` will subsequently becomes:

```json
[
    [
        "1"
    ],
    [
        "text"
    ]
]
```

Then using the following template:

![image](https://user-images.githubusercontent.com/9417900/97156299-7edd1380-17b1-11eb-80ab-0d0e656b8e45.png)


And you will get the following result(the condition of `status-1` is false):

![image](https://user-images.githubusercontent.com/9417900/97156321-869cb800-17b1-11eb-9352-047ca1cbf47a.png)

P.S. If you use the origin data, you will get the following result(all the conditions are true):

![image](https://user-images.githubusercontent.com/9417900/97156456-ae8c1b80-17b1-11eb-98a2-151832748bb4.png)

**Comment by sandeep59** [comment]
But in the sample message I have provided its "I" only in PV1-2, then PV1-2, PV1-2-1 and PV1-2-1-1 all should be true

**Comment by ACMoretxj** [comment]
> But in the sample message I have provided its "I" only in PV1-2, then PV1-2, PV1-2-1 and PV1-2-1-1 all should be true

Yes, only a value of `[['I']]` for `PV1-2` will not break the conditions. You said you have customized the templates, can you give me the template after your customization?

**Comment by sandeep59** [comment]
> > But in the sample message I have provided its "I" only in PV1-2, then PV1-2, PV1-2-1 and PV1-2-1-1 all should be true
> 
> Yes, only a value of `[['I']]` for `PV1-2` will not break the conditions. You said you have customized the templates, can you give me the template after your customization?

using the attached template, I am unable to pick data from PID-8, which is patient gender, I have to use PID-8-1-1 to get the data. Please check
[Patient_resource.txt](https://github.com/microsoft/FHIR-Converter/files/5443458/Patient_resource.txt)

**Comment by ACMoretxj** [comment]
> > > But in the sample message I have provided its "I" only in PV1-2, then PV1-2, PV1-2-1 and PV1-2-1-1 all should be true
> > 
> > 
> > Yes, only a value of `[['I']]` for `PV1-2` will not break the conditions. You said you have customized the templates, can you give me the template after your customization?
> 
> using the attached template, I am unable to pick data from PID-8, which is patient gender, I have to use PID-8-1-1 to get the data. Please check
> [Patient_resource.txt](https://github.com/microsoft/FHIR-Converter/files/5443458/Patient_resource.txt)

Hi, the problem you encountered about `PID-8` is exactly the same with `PV1-2`(`[['M']]` vs. `[['I']]`). Please refer the [HL7V2 spec](https://www.hl7.org/implement/standards/product_brief.cfm?product_id=185) for more details.

**Comment by sandeep59** [comment]
Hi, 
Yes, both issues are same, It should pick up information using PID-8, PID-8-1,PID-8-1-1  as we only receive a single value in PID-8 either "M" or "F"
But it is only true when I use PID-8-1-1

**Comment by ACMoretxj** [comment]
It seems that some modifications influence the comparison logic. How about trying to downgrade the FHIR-Converter project to the [online master version](https://github.com/microsoft/FHIR-Converter) and see whether the behaviors can meet your expection or not?

If the behaviors are normal, then try to append your customizations step by step to see which part is the actual reason :-)

**Comment by ACMoretxj** [comment]
Now close this issue, please feel free to reopen it for any questions.
