### ISSUE TITLE
Need a helper to set variable in templates

### ISSUE THREAD

**Issue by sandeep59** [microsoft/FHIR-Converter#92]
While customizing the templates as per our requirements, we often require to store some value and reuse it somewhere else , may be converting another segment into FHIR resource. Is there any feature or helper which can store value and can be reused?

**Comment by CaitlinV39** [comment]
@sandeep59 thank you so much for bringing this up. @ranvijaykumar going to unassign myself and let you triage.

**Comment by ranvijaykumar** [comment]
@sandeep59 we do not have any feature to store value in a variable. By the way, we are soon releasing a new converter engine based on Liquid, which has the ability to store values in variables.

**Comment by sandeep59** [comment]
May I please know how soon you are releasing the new version?

**Comment by ranvijaykumar** [comment]
Within a couple of weeks.

**Comment by sandeep59** [comment]
Great!!
